version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=$DATABASE_URL
        - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
        - GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
        - BASE_URL=$BASE_URL
        - CLIENT_URL=$CLIENT_URL
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_SERVER_URL=$VITE_SERVER_URL
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
    command: npm run dev

  db:
    image: postgres
    ports:
      - "3306:3306"
