name: Docker Build And Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build backend Docker image
      working-directory: ./backend
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        BASE_URL: ${{ secrets.BASE_URL }}
        CLIENT_URL: ${{ secrets.CLIENT_URL }}
      run: docker build . --file Dockerfile --tag maneeshwije/markdown-edit-backend
    
    - uses: actions/checkout@v3
    - name: Build frontend Docker image
      working-directory: ./frontend
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        BASE_URL: ${{ secrets.BASE_URL }}
        CLIENT_URL: ${{ secrets.CLIENT_URL }}
      run: docker build . --file Dockerfile --tag maneeshwije/markdown-edit-frontend
      
    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker images to DockerHub
      run: docker push maneeshwije/markdown-edit-backend && docker push maneeshwije/markdown-edit-frontend
