name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SQLx CLI
      run: |
        cargo install sqlx-cli --no-default-features --features native-tls,postgres

    - name: Run Database Migrations
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        cd backend
        sqlx migrate run

    - name: Build
      run: |
        cd backend
        cargo build --verbose

    - name: Run tests
      run: |
        cd backend
        cargo test --verbose
