name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
    - name: Build
      run: cd backend && cargo install sqlx-cli --features postgres,tls-native-tls,runtime-tokio,uuid,migrate,time && sqlx migrate run && cargo build --verbose
    - name: Run tests
      run: cd backend && cargo test --verbose
